import { describe, it, expect } from "vitest";
import { generateExample } from "../../src/commands/generate.js";
import type { EnvSchema } from "../../src/schema/types.js";

describe("generateExample", () => {
  const schema: EnvSchema = {
    version: 1,
    variables: {
      NODE_ENV: {
        type: "enum",
        required: true,
        values: ["development", "production"],
        default: "development",
        description: "Application environment",
      },
      PORT: {
        type: "integer",
        required: true,
        default: 3000,
      },
      DB_URL: {
        type: "url",
        required: true,
        sensitive: true,
        description: "Database connection",
      },
      DEBUG: {
        type: "boolean",
        required: false,
      },
    },
  };

  it("includes descriptions as comments", () => {
    const output = generateExample(schema);
    expect(output).toContain("# Application environment");
    expect(output).toContain("# Database connection");
  });

  it("uses defaults when available", () => {
    const output = generateExample(schema);
    expect(output).toContain("NODE_ENV=development");
    expect(output).toContain("PORT=3000");
  });

  it("generates placeholder for sensitive vars", () => {
    const output = generateExample(schema);
    expect(output).toContain("DB_URL=<your-db-url>");
  });

  it("uses type-appropriate placeholder for boolean", () => {
    const output = generateExample(schema);
    expect(output).toContain("DEBUG=false");
  });

  it("includes header comment", () => {
    const output = generateExample(schema);
    expect(output).toContain("# Generated by Envalid");
  });
});
