import { describe, it, expect, beforeEach } from "vitest";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { readLockfile } from "../../src/core/lockfile.js";

describe("readLockfile — pnpm v9", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-pnpm-"));
  });

  it("reads resolved versions from importers.*", async () => {
    await fs.writeFile(
      path.join(tmp, "pnpm-lock.yaml"),
      `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      next:
        specifier: ^15.1.0
        version: 15.1.2
      react:
        specifier: ^19.0.0
        version: 19.0.0
    devDependencies:
      typescript:
        specifier: ^5.5.0
        version: 5.5.4
`,
    );
    const map = await readLockfile(tmp);
    expect(map.get("next")).toBe("15.1.2");
    expect(map.get("react")).toBe("19.0.0");
    expect(map.get("typescript")).toBe("5.5.4");
  });

  it("strips pnpm's peer-version suffix from resolved versions", async () => {
    await fs.writeFile(
      path.join(tmp, "pnpm-lock.yaml"),
      `lockfileVersion: '9.0'
importers:
  .:
    devDependencies:
      tsup:
        specifier: ^8.5.1
        version: 8.5.1(postcss@8.5.9)(typescript@6.0.2)
`,
    );
    const map = await readLockfile(tmp);
    expect(map.get("tsup")).toBe("8.5.1");
  });
});

describe("readLockfile — npm v3", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-npm-"));
  });

  it("reads top-level dependencies from packages tree", async () => {
    await fs.writeFile(
      path.join(tmp, "package-lock.json"),
      JSON.stringify({
        lockfileVersion: 3,
        packages: {
          "": { name: "root", version: "0.0.0" },
          "node_modules/next": { version: "14.2.10" },
          "node_modules/react": { version: "18.3.1" },
          "node_modules/react/node_modules/nested": { version: "9.9.9" },
        },
      }),
    );
    const map = await readLockfile(tmp);
    expect(map.get("next")).toBe("14.2.10");
    expect(map.get("react")).toBe("18.3.1");
    // Nested duplicate — must NOT shadow top-level.
    expect(map.get("nested")).toBeUndefined();
  });
});

describe("readLockfile — yarn classic", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-yarn-"));
  });

  it("reads the version field under each header", async () => {
    await fs.writeFile(
      path.join(tmp, "yarn.lock"),
      `# THIS IS AN AUTOGENERATED FILE.

"next@^15.1.0":
  version "15.1.2"
  resolved "https://registry/next-15.1.2.tgz"

react@^19.0.0:
  version "19.0.0"
  resolved "https://registry/react-19.0.0.tgz"
`,
    );
    const map = await readLockfile(tmp);
    expect(map.get("next")).toBe("15.1.2");
    expect(map.get("react")).toBe("19.0.0");
  });
});

describe("readLockfile — yarn berry", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-berry-"));
  });

  it("parses berry's `foo@npm:range` headers and ignores __metadata", async () => {
    await fs.writeFile(
      path.join(tmp, "yarn.lock"),
      `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10

"next@npm:^15.1.0":
  version: 15.1.2
  resolution: "next@npm:15.1.2"

"react@npm:^19.0.0":
  version: 19.0.0
  resolution: "react@npm:19.0.0"
`,
    );
    const map = await readLockfile(tmp);
    expect(map.get("next")).toBe("15.1.2");
    expect(map.get("react")).toBe("19.0.0");
    // __metadata must not be captured as a package name.
    expect(map.has("__metadata")).toBe(false);
  });

  it("handles scoped packages in yarn headers", async () => {
    await fs.writeFile(
      path.join(tmp, "yarn.lock"),
      `"@types/node@^20":
  version "20.11.0"
`,
    );
    const map = await readLockfile(tmp);
    expect(map.get("@types/node")).toBe("20.11.0");
  });
});

describe("readLockfile — priority when multiple lockfiles exist", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-multi-"));
  });

  it("prefers pnpm-lock.yaml over package-lock.json and yarn.lock", async () => {
    await fs.writeFile(
      path.join(tmp, "pnpm-lock.yaml"),
      `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      next:
        specifier: ^15.1.0
        version: 15.2.0
`,
    );
    await fs.writeFile(
      path.join(tmp, "package-lock.json"),
      JSON.stringify({
        lockfileVersion: 3,
        packages: { "node_modules/next": { version: "14.0.0" } },
      }),
    );
    await fs.writeFile(
      path.join(tmp, "yarn.lock"),
      `"next@^15.0.0":\n  version "13.0.0"\n`,
    );
    const map = await readLockfile(tmp);
    // pnpm wins.
    expect(map.get("next")).toBe("15.2.0");
  });
});

describe("readLockfile — fallback", () => {
  let tmp: string;
  beforeEach(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), "aware-lockfile-none-"));
  });

  it("returns empty map when no lockfile present", async () => {
    const map = await readLockfile(tmp);
    expect(map.size).toBe(0);
  });

  it("returns empty map when lockfile is unparseable", async () => {
    await fs.writeFile(path.join(tmp, "pnpm-lock.yaml"), "nope: :: :: nonsense");
    const map = await readLockfile(tmp);
    // Either empty from parse error, or empty from missing expected shape.
    expect(map.size).toBe(0);
  });
});
