import type { EnvSchema } from "../schema/types.js";
import { writeFileSync } from "node:fs";

export function generateExample(schema: EnvSchema): string {
  const lines: string[] = [
    "# Generated by Envalid",
    "# Do not edit manually — regenerate with: envalid generate-example",
    "",
  ];

  for (const [name, varSchema] of Object.entries(schema.variables)) {
    if (varSchema.description) {
      lines.push(`# ${varSchema.description}`);
    }

    let placeholder: string;
    if (varSchema.default !== undefined) {
      placeholder = String(varSchema.default);
    } else if (varSchema.sensitive) {
      placeholder = `<your-${name.toLowerCase().replace(/_/g, "-")}>`;
    } else if (varSchema.type === "enum" && varSchema.values) {
      placeholder = varSchema.values[0];
    } else if (varSchema.type === "boolean") {
      placeholder = "false";
    } else if (varSchema.type === "integer") {
      placeholder = "0";
    } else if (varSchema.type === "float") {
      placeholder = "0.0";
    } else {
      placeholder = `<${varSchema.type}>`;
    }

    lines.push(`${name}=${placeholder}`);
    lines.push("");
  }

  return lines.join("\n");
}

export interface GenerateExampleOptions {
  schema: EnvSchema;
  outputPath: string;
}

export function runGenerateExample(options: GenerateExampleOptions): string {
  const content = generateExample(options.schema);
  writeFileSync(options.outputPath, content, "utf-8");
  return content;
}
