import type { EnvSchema, VariableSchema } from "../schema/types.js";
import { getDefaultRegistry, type Registry } from "../runtime/registry.js";
import { registerBuiltins } from "../runtime/builtins.js";

export type CodegenRuntime = "process" | "import-meta";

export interface CodegenOptions {
  /** Source expression base. Default "process.env". */
  runtime?: CodegenRuntime;
  /** Schema file path to reference in header comment. */
  schemaPath?: string;
  registry?: Registry;
}

let ensured = false;
function ensureBuiltins(): void {
  if (ensured) return;
  registerBuiltins(getDefaultRegistry());
  ensured = true;
}

export function generateTypedClient(
  schema: EnvSchema,
  options: CodegenOptions = {},
): string {
  ensureBuiltins();
  const registry = options.registry ?? getDefaultRegistry();
  const runtime = options.runtime ?? "process";
  const accessor =
    runtime === "import-meta"
      ? (name: string) => `import.meta.env.${name}`
      : (name: string) => `process.env.${name}`;

  const lines: string[] = [];
  lines.push("// Generated by @whenlabs/envalid — DO NOT EDIT BY HAND.");
  if (options.schemaPath) {
    lines.push(`// Source schema: ${options.schemaPath}`);
  }
  lines.push("// prettier-ignore");
  lines.push("/* eslint-disable */");
  lines.push("");
  lines.push("export const env = Object.freeze({");

  const entries = Object.entries(schema.variables).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  for (const [name, v] of entries) {
    lines.push(`  ${name}: ${buildAccessExpr(name, v, registry, accessor)},`);
  }

  lines.push("} as const);");
  lines.push("");
  lines.push("export type Env = typeof env;");
  lines.push("");
  lines.push("// Explicit type surface — useful when you want to annotate an");
  lines.push("// API that consumes env without depending on the concrete object.");
  lines.push("export interface EnvShape {");
  for (const [name, v] of entries) {
    const opt = isOptional(v) ? "?" : "";
    lines.push(`  ${name}${opt}: ${tsTypeFor(v, registry)};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function buildAccessExpr(
  name: string,
  v: VariableSchema,
  registry: Registry,
  accessor: (name: string) => string,
): string {
  const base = accessor(name);
  const hasDefault = v.default !== undefined;
  const optional = isOptional(v);
  const raw = hasDefault
    ? `(${base} ?? ${JSON.stringify(String(v.default))})`
    : optional
      ? base
      : `${base}!`;
  return wrapForType(raw, v, registry);
}

function wrapForType(
  raw: string,
  v: VariableSchema,
  registry: Registry,
): string {
  const def = registry.getValidator(v.type);
  const hint = def?.typeHint;
  const typeName = tsTypeFor(v, registry);
  if (v.type === "enum") {
    return `(${raw} as ${typeName})`;
  }
  if (v.type === "csv") {
    return isOptional(v)
      ? `(${raw} ? ${raw}.split(',') : undefined) as ${typeName}`
      : `${raw}.split(',') as ${typeName}`;
  }
  if (hint === "number") {
    return isOptional(v)
      ? `(${raw} === undefined ? undefined : Number(${raw})) as ${typeName}`
      : `Number(${raw}) as ${typeName}`;
  }
  if (hint === "boolean") {
    return isOptional(v)
      ? `(${raw} === undefined ? undefined : ['true', '1'].includes(String(${raw}).toLowerCase())) as ${typeName}`
      : `['true', '1'].includes(String(${raw}).toLowerCase()) as ${typeName}`;
  }
  if (hint === "json") {
    return isOptional(v)
      ? `(${raw} === undefined ? undefined : JSON.parse(${raw})) as ${typeName}`
      : `JSON.parse(${raw}) as ${typeName}`;
  }
  return `${raw} as ${typeName}`;
}

function tsTypeFor(v: VariableSchema, registry: Registry): string {
  if (v.type === "enum" && v.values && v.values.length > 0) {
    return v.values.map((x) => JSON.stringify(x)).join(" | ");
  }
  if (v.type === "csv") return "readonly string[]";
  const def = registry.getValidator(v.type);
  switch (def?.typeHint) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    case "array":
      return "readonly string[]";
    default:
      return "string";
  }
}

function isOptional(v: VariableSchema): boolean {
  return v.required === false && v.default === undefined;
}
