import { describe, it, expect } from 'vitest';
import { parseCargoLock, parseDependencyName } from '../../src/resolvers/cargo-lock.js';

describe('parseCargoLock', () => {
  it('parses a v3 lockfile with external packages and deps', () => {
    const lock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = [
 "serde",
 "tokio",
]

[[package]]
name = "serde"
version = "1.0.188"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "tokio"
version = "1.32.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def"
dependencies = [
 "serde",
]
`;
    const packages = parseCargoLock(lock);
    expect(packages).toHaveLength(3);

    const [app, serde, tokio] = packages;
    expect(app!.name).toBe('my-app');
    expect(app!.source).toBeUndefined();
    expect(app!.dependencies).toEqual(['serde', 'tokio']);

    expect(serde!.name).toBe('serde');
    expect(serde!.version).toBe('1.0.188');
    expect(serde!.source).toContain('crates.io-index');
    expect(serde!.dependencies).toEqual([]);

    expect(tokio!.dependencies).toEqual(['serde']);
  });

  it('handles inline array dependencies', () => {
    const lock = `[[package]]
name = "a"
version = "1.0.0"
dependencies = ["b", "c"]
`;
    const packages = parseCargoLock(lock);
    expect(packages[0]!.dependencies).toEqual(['b', 'c']);
  });

  it('ignores comments and blank lines', () => {
    const lock = `# top comment
# another

[[package]]
name = "x"
version = "0.1.0"
# inline comment
source = "registry+https://github.com/rust-lang/crates.io-index"
`;
    const packages = parseCargoLock(lock);
    expect(packages).toHaveLength(1);
    expect(packages[0]!.name).toBe('x');
  });

  it('handles the final package with no trailing newline', () => {
    const lock = `[[package]]
name = "only"
version = "1.0.0"`;
    const packages = parseCargoLock(lock);
    expect(packages).toHaveLength(1);
    expect(packages[0]!.name).toBe('only');
  });

  it('returns empty array for empty input', () => {
    expect(parseCargoLock('')).toEqual([]);
    expect(parseCargoLock('# just a comment')).toEqual([]);
  });

  it('skips malformed entries missing name or version', () => {
    const lock = `[[package]]
name = "has-name"

[[package]]
version = "1.0.0"

[[package]]
name = "complete"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;
    const packages = parseCargoLock(lock);
    expect(packages).toHaveLength(1);
    expect(packages[0]!.name).toBe('complete');
  });
});

describe('parseDependencyName', () => {
  it('returns the full string when no version is given', () => {
    expect(parseDependencyName('serde')).toBe('serde');
  });

  it('strips version suffix', () => {
    expect(parseDependencyName('serde 1.0.188')).toBe('serde');
  });

  it('strips version and source', () => {
    expect(parseDependencyName('serde 1.0.188 (registry+https://example.com)')).toBe('serde');
  });
});
