import { describe, it, expect } from 'vitest';
import { parsePoetryLock } from '../../src/resolvers/poetry-lock.js';

describe('parsePoetryLock', () => {
  it('parses top-level [[package]] entries', () => {
    const lock = `# Auto-generated by Poetry
[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false

[[package]]
name = "urllib3"
version = "2.0.7"
optional = false
`;
    const packages = parsePoetryLock(lock);
    expect(packages).toHaveLength(2);
    expect(packages[0]!.name).toBe('requests');
    expect(packages[0]!.version).toBe('2.31.0');
    expect(packages[0]!.optional).toBe(false);
    expect(packages[1]!.name).toBe('urllib3');
  });

  it('captures direct dependencies from [package.dependencies]', () => {
    const lock = `[[package]]
name = "requests"
version = "2.31.0"

[package.dependencies]
charset-normalizer = ">=2,<4"
urllib3 = ">=1.21.1,<3"

[[package]]
name = "urllib3"
version = "2.0.7"
`;
    const packages = parsePoetryLock(lock);
    expect(packages).toHaveLength(2);
    // [package.dependencies] fields do NOT overwrite the parent's name/version.
    expect(packages[0]!.name).toBe('requests');
    expect(packages[0]!.version).toBe('2.31.0');
    expect(packages[0]!.dependencies).toEqual(['charset-normalizer', 'urllib3']);
    expect(packages[1]!.name).toBe('urllib3');
    expect(packages[1]!.dependencies).toEqual([]);
  });

  it('captures nested [package.dependencies.NAME] subtables without leaking their fields', () => {
    const lock = `[[package]]
name = "requests"
version = "2.31.0"

[package.dependencies.certifi]
version = ">=2017.4.17"
python-versions = ">=3.7"

[package.dependencies.idna]
version = ">=2.5,<4"

[[package]]
name = "idna"
version = "3.4"
`;
    const packages = parsePoetryLock(lock);
    expect(packages).toHaveLength(2);
    // certifi + idna were captured as deps; the nested subtable's `version`
    // and `python-versions` keys did NOT leak into the parent package's
    // name/version or into `idna`'s.
    expect(packages[0]!.name).toBe('requests');
    expect(packages[0]!.version).toBe('2.31.0');
    expect(packages[0]!.dependencies).toEqual(['certifi', 'idna']);
    expect(packages[1]!.version).toBe('3.4');
  });

  it('handles inline-table dependency values like pkg = {version = "..."}', () => {
    const lock = `[[package]]
name = "x"
version = "1.0.0"

[package.dependencies]
foo = {version = ">=1", optional = true}
bar = "^2"
`;
    const packages = parsePoetryLock(lock);
    expect(packages[0]!.dependencies).toEqual(['foo', 'bar']);
  });

  it('dedupes dependencies (inline + nested subtable for same dep)', () => {
    const lock = `[[package]]
name = "x"
version = "1.0.0"

[package.dependencies]
foo = ">=1"

[package.dependencies.foo]
version = ">=1"
python = ">=3.7"
`;
    const packages = parsePoetryLock(lock);
    expect(packages[0]!.dependencies).toEqual(['foo']);
  });

  it('captures optional = true', () => {
    const lock = `[[package]]
name = "extra"
version = "1.0.0"
optional = true
`;
    const packages = parsePoetryLock(lock);
    expect(packages[0]!.optional).toBe(true);
  });

  it('captures category = "dev"', () => {
    const lock = `[[package]]
name = "pytest"
version = "7.0.0"
category = "dev"
`;
    const packages = parsePoetryLock(lock);
    expect(packages[0]!.category).toBe('dev');
  });

  it('skips packages missing name or version', () => {
    const lock = `[[package]]
name = "incomplete"

[[package]]
name = "good"
version = "1.0.0"
`;
    const packages = parsePoetryLock(lock);
    expect(packages).toHaveLength(1);
    expect(packages[0]!.name).toBe('good');
  });

  it('ignores poetry metadata section', () => {
    const lock = `[[package]]
name = "real"
version = "1.0.0"

[metadata]
lock-version = "2.0"
python-versions = ">=3.8"
content-hash = "abc"

[metadata.files]
real = [
  {file = "x.whl", hash = "sha256:..."},
]
`;
    const packages = parsePoetryLock(lock);
    expect(packages).toHaveLength(1);
    expect(packages[0]!.name).toBe('real');
  });
});
