import { describe, it, expect } from "vitest";
import { ClaudeGenerator } from "../../src/generators/claude.js";
import { composeContext } from "../../src/generators/composer.js";
import type { DetectedStack, AwareConfig, Fragment } from "../../src/types.js";

function makeStackItem(name: string, variant: string | null = null) {
  return {
    name,
    version: "1.0",
    variant,
    confidence: 0.95,
    detectedFrom: "test",
  };
}

function makeConfig(): AwareConfig {
  return {
    version: 1,
    project: { name: "test-project", description: "A test project", architecture: "monolith" },
    stack: {
      framework: "nextjs@15.1:app-router",
      language: "typescript@5.5",
      styling: "tailwindcss@4.0",
      orm: "drizzle@0.34",
      database: "postgres",
      testing: ["vitest@3.0", "playwright@1.48"],
      linting: ["eslint@9.0:flat-config", "prettier@3.4"],
      packageManager: "pnpm",
      monorepo: null,
      deployment: "vercel",
      auth: "nextauth@5.0",
      apiStyle: "trpc@11.0",
    },
    conventions: {
      naming: { files: "kebab-case", components: "PascalCase" },
    },
    rules: ["Use server components by default", "Colocate related files"],
    structure: { "src/app": "App router pages", "src/lib": "Shared utilities" },
    targets: { claude: true, cursor: true, copilot: false, agents: false },
    _meta: {
      createdAt: new Date().toISOString(),
      lastSyncedAt: null,
      lastDetectionHash: "",
      awareVersion: "0.1.0",
    },
  };
}

function makeStack(): DetectedStack {
  return {
    framework: makeStackItem("nextjs", "app-router"),
    language: makeStackItem("typescript"),
    styling: makeStackItem("tailwindcss"),
    orm: makeStackItem("drizzle"),
    database: makeStackItem("postgres"),
    testing: [makeStackItem("vitest"), makeStackItem("playwright")],
    linting: [makeStackItem("eslint"), makeStackItem("prettier")],
    packageManager: makeStackItem("pnpm"),
    monorepo: null,
    deployment: makeStackItem("vercel"),
    auth: makeStackItem("nextauth"),
    apiStyle: makeStackItem("trpc"),
  };
}

describe("ClaudeGenerator", () => {
  it("generates output with expected sections", () => {
    const config = makeConfig();
    const stack = makeStack();
    const fragments: Fragment[] = [
      {
        id: "nextjs-15",
        category: "framework",
        title: "Next.js 15",
        content: "## Next.js 15\n- Use App Router\n- Prefer server components",
        priority: 10,
      },
    ];

    const context = composeContext(stack, config, fragments);
    const generator = new ClaudeGenerator();
    const result = generator.generate(context);

    expect(result.target).toBe("claude");
    expect(result.filePath).toBe("CLAUDE.md");
    expect(result.sections).toBeGreaterThan(0);

    // Contains project section
    expect(result.content).toContain("test-project");

    // Contains stack section
    expect(result.content).toContain("Tech Stack");

    // Contains fragment content
    expect(result.content).toContain("Next.js 15");

    // Contains conventions
    expect(result.content).toContain("Conventions");

    // Contains rules
    expect(result.content).toContain("Rules");
    expect(result.content).toContain("Use server components by default");

    // Contains structure
    expect(result.content).toContain("Project Structure");

    // Has footer
    expect(result.content).toContain("Generated by Aware");

    // No duplicate headers (## Tech Stack should appear exactly once)
    const techStackMatches = result.content.match(/## Tech Stack/g);
    expect(techStackMatches).toHaveLength(1);
  });
});
