import { TARGETS } from "../constants.js";
import type { ComposedContext, GeneratorResult, TargetName } from "../types.js";
import { BaseGenerator } from "./base.js";

const FOOTER = `\n---\n<!-- Generated by Aware. Edit .aware.json and run \`aware sync\`. -->`;

export class ClaudeGenerator extends BaseGenerator {
  readonly target: TargetName = "claude";
  readonly filePath: string = TARGETS.claude.file;

  generate(context: ComposedContext): GeneratorResult {
    const sections: string[] = [];

    if (context.projectSection) sections.push(context.projectSection);
    if (context.stackSection) sections.push(context.stackSection);

    for (const fragment of context.fragmentSections) {
      if (fragment.content) {
        sections.push(`## ${fragment.title}\n${fragment.content}`);
      }
    }

    if (context.conventionsSection) sections.push(context.conventionsSection);
    if (context.rulesSection) sections.push(context.rulesSection);
    if (context.structureSection) sections.push(context.structureSection);

    const content = sections.join("\n\n") + FOOTER;

    return {
      target: this.target,
      filePath: this.filePath,
      content,
      sections: sections.length,
    };
  }
}
