import { TARGETS } from "../constants.js";
import type { ComposedContext, GeneratorResult, TargetName } from "../types.js";
import { BaseGenerator } from "./base.js";

const FOOTER = `\n---\n<!-- Generated by Aware. Edit .aware.json and run \`aware sync\`. -->`;

/**
 * Trim markdown content to the first `maxLines` bullet points / lines.
 * Non-bullet lines (headings, blank) pass through freely; only "- " lines are counted.
 */
export function trimFragment(content: string, maxLines: number): string {
  if (!content) return "";

  const lines = content.split("\n");
  const result: string[] = [];
  let bulletCount = 0;

  for (const line of lines) {
    const isBullet = line.trimStart().startsWith("- ");
    if (isBullet) {
      if (bulletCount >= maxLines) continue;
      bulletCount++;
    }
    result.push(line);
  }

  return result.join("\n");
}

export class CopilotGenerator extends BaseGenerator {
  readonly target: TargetName = "copilot";
  readonly filePath: string = TARGETS.copilot.file;

  generate(context: ComposedContext): GeneratorResult {
    const sections: string[] = [];

    if (context.projectSection) sections.push(context.projectSection);
    if (context.stackSection) sections.push(context.stackSection);

    for (const fragment of context.fragmentSections) {
      if (fragment.content) {
        const trimmed = trimFragment(fragment.content, 5);
        sections.push(trimmed);
      }
    }

    if (context.conventionsSection) sections.push(context.conventionsSection);
    if (context.rulesSection) sections.push(context.rulesSection);
    if (context.structureSection) sections.push(context.structureSection);

    const content = sections.join("\n\n") + FOOTER;

    return {
      target: this.target,
      filePath: this.filePath,
      content,
      sections: sections.length,
    };
  }
}
