import type { ScanResult } from '../types.js';
import type { CheckResult } from '../policy/types.js';

export function toMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# Vow Report');
  lines.push('');
  lines.push(`**Project:** ${result.project.name}@${result.project.version}`);
  lines.push(`**Scanned:** ${result.timestamp}`);
  lines.push(`**Ecosystems:** ${result.ecosystems.join(', ')}`);
  lines.push(`**Total packages:** ${result.summary.total}`);
  lines.push('');

  // License summary table
  lines.push('## License Summary');
  lines.push('');
  lines.push('| License | Count | % |');
  lines.push('|---------|------:|--:|');

  const sorted = [...result.summary.byLicense.entries()]
    .sort((a, b) => b[1] - a[1]);

  for (const [license, count] of sorted) {
    const pct = ((count / result.summary.total) * 100).toFixed(1);
    lines.push(`| ${license} | ${count} | ${pct}% |`);
  }

  lines.push('');

  // Attention section
  const copyleftCount = (result.summary.byCategory.get('strongly-copyleft') ?? 0)
    + (result.summary.byCategory.get('network-copyleft') ?? 0);

  if (copyleftCount > 0 || result.summary.unknown > 0 || result.summary.custom > 0) {
    lines.push('## Attention Required');
    lines.push('');
    if (copyleftCount > 0) {
      lines.push(`- :x: **${copyleftCount}** packages with copyleft licenses`);
    }
    if (result.summary.unknown > 0) {
      lines.push(`- :warning: **${result.summary.unknown}** packages with unknown license`);
    }
    if (result.summary.custom > 0) {
      lines.push(`- :warning: **${result.summary.custom}** packages with custom/non-SPDX license`);
    }
    lines.push('');
  }

  // Full package list (collapsible)
  lines.push('<details>');
  lines.push('<summary>Full Package List</summary>');
  lines.push('');
  lines.push('| Package | Version | License | Category | Type |');
  lines.push('|---------|---------|---------|----------|------|');

  const sortedPkgs = [...result.packages].sort((a, b) => a.name.localeCompare(b.name));
  for (const pkg of sortedPkgs) {
    const license = pkg.license.spdxExpression ?? 'UNKNOWN';
    lines.push(`| ${pkg.name} | ${pkg.version} | ${license} | ${pkg.license.category} | ${pkg.dependencyType} |`);
  }

  lines.push('');
  lines.push('</details>');
  lines.push('');

  return lines.join('\n');
}

export function toMarkdownCheckResult(result: CheckResult): string {
  const lines: string[] = [];

  // Summary for PR comment — keep it concise
  const icon = result.passed ? ':white_check_mark:' : ':x:';
  lines.push(`## ${icon} License Compliance Check`);
  lines.push('');
  lines.push(`| Status | Count |`);
  lines.push(`|--------|------:|`);
  lines.push(`| Blocked | ${result.summary.blocked} |`);
  lines.push(`| Warnings | ${result.summary.warnings} |`);
  lines.push(`| Passed | ${result.summary.allowed} |`);
  lines.push(`| **Total** | **${result.summary.total}** |`);
  lines.push('');

  if (result.blocked.length > 0) {
    lines.push('### Blocked');
    lines.push('');
    for (const item of result.blocked) {
      const license = item.pkg.license.spdxExpression ?? 'UNKNOWN';
      lines.push(`- :x: **${item.pkg.name}@${item.pkg.version}** (${license})`);
      if (item.matchedRule) {
        lines.push(`  - Rule: _"${item.matchedRule.originalText}"_`);
      }
      if (item.dependencyPath.length > 0) {
        lines.push(`  - Path: ${item.dependencyPath.join(' → ')}`);
      }
    }
    lines.push('');
  }

  if (result.warnings.length > 0) {
    lines.push('### Warnings');
    lines.push('');
    for (const item of result.warnings) {
      const license = item.pkg.license.spdxExpression ?? 'UNKNOWN';
      lines.push(`- :warning: **${item.pkg.name}@${item.pkg.version}** (${license})`);
      if (item.matchedRule) {
        lines.push(`  - Rule: _"${item.matchedRule.originalText}"_`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by [Vow](https://github.com/vow-cli/vow)_');
  lines.push('');

  return lines.join('\n');
}
